<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>${title}</title>
    <style>
        @page {
            size: A4 ${pageOrientation!"portrait"};
            margin: 2cm;
        }

        body {
            font-family: 'Arial', sans-serif;
            color: #333;
            line-height: 1.6;
        }

        h1 {
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        h2 {
            color: #34495e;
            margin-top: 25px;
            margin-bottom: 15px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .info-section {
            background-color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }

        .info-section p {
            margin: 5px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        table thead {
            background-color: #3498db;
            color: white;
        }

        table th, table td {
            padding: 12px;
            text-align: left;
            border: 1px solid #ddd;
        }

        table tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        table tbody tr:hover {
            background-color: #f5f5f5;
        }

        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 0.9em;
            color: #7f8c8d;
        }

        .summary {
            background-color: #e8f5e9;
            padding: 15px;
            border-left: 4px solid #4caf50;
            margin: 20px 0;
        }

        .label {
            font-weight: bold;
            color: #2c3e50;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>${title}</h1>
        <#if subtitle??>
            <p style="font-size: 1.2em; color: #7f8c8d;">${subtitle}</p>
        </#if>
    </div>

    <div class="info-section">
        <p><span class="label">Generated on:</span> ${generatedDate}</p>
        <#if author??>
            <p><span class="label">Author:</span> ${author}</p>
        </#if>
        <#if description??>
            <p><span class="label">Description:</span> ${description}</p>
        </#if>
    </div>

    <#if items?? && items?size gt 0>
        <h2>Items</h2>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Quantity</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                <#list items as item>
                    <tr>
                        <td>${item.id}</td>
                        <td>${item.name}</td>
                        <td>${item.description!"N/A"}</td>
                        <td>${item.quantity}</td>
                        <td>$${item.price?string["0.00"]}</td>
                    </tr>
                </#list>
            </tbody>
        </table>

        <#if total??>
            <div class="summary">
                <p style="font-size: 1.2em; margin: 0;">
                    <span class="label">Total:</span> $${total?string["0.00"]}
                </p>
            </div>
        </#if>
    </#if>

    <#if sections?? && sections?size gt 0>
        <#list sections as section>
            <h2>${section.title}</h2>
            <p>${section.content}</p>
        </#list>
    </#if>

    <div class="footer">
        <p>This report was automatically generated by Jambock Reports Engine</p>
        <p>Powered by Freemarker and Flying Saucer</p>
    </div>
</body>
</html>

